server:
  port: 12051
  context-path: /ui
  session:
    cookie:
      name: UISESSION

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ClientId
      clientSecret: secret
      accessTokenUri: http://localhost:12050/auth/oauth/token
      userAuthorizationUri: http://localhost:12050/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:12050/auth/rest/resource

spring:
  thymeleaf:
    cache: false